### ISSUE TITLE
Publish to PyPi.org

### ISSUE THREAD

**Issue by codeclinic** [Ligio/hacc-ozmo#1]
Is there any chance you can publish this to PyPi.org so that it can be used in Home Assistant etc?

Thanks.

**Comment by Ligio** [comment]
Hi @codeclinic!
The ozmo library is already published to PyPi ==> https://pypi.org/project/ozmo/
If you want to use this **H**ome **A**ssistant **C**ustom **C**omponent you should only copy the folder **custom_components** to your config directory (/config for hass.io or ~/.homeassistant for other so) and put this configuration in your configuration.yaml file:

```
deebot:
  username: YOUR_ECOVACS_USERNAME
  password: YOUR_ECOVACS_PASSWORD
  country: YOUR_TWO_LETTER_COUNTRY_CODE
  continent: YOUR_TWO_LETTER_CONTINENT_CODE
```
