### ISSUE TITLE
Error with configuration

### ISSUE THREAD

**Issue by 0endive** [Ligio/hacc-ozmo#42]
Hello,

I am trying to setup custom areas and ran into problem. Please see configuration below it works fine without the vacuum-script-clean-area once I add it, I can’t restart HA.

deebot:
  username: username
  password: password
  country: XX
  continent: XX
  supported_features:
  - start
  - pause
  - stop
  - return_home
  - fan_speed
  - battery
  - status
  - send_command
  - locate
  - clean_spot
  - turn_on
  - turn_off
  vacuum_script_clean_area:
    alias: living_room
    sequence:
    - service: vacuum.send_command
      data:
        command: spot_area
        entity_id: vacuum.deebot
        params:
          area: 0

**Comment by Swanky-Bubbles** [comment]
Looks like you have the script under the deebot domain and not script. 

Your config should look like this

```
deebot:
  username: username
  password: password
  country: XX
  continent: XX
  supported_features:
      - start
      - pause
      - stop
      - return_home
      - fan_speed
      - battery
      - status
      - send_command
      - locate
      - clean_spot
      - turn_on
      - turn_off
script:     
  vacuum_script_clean_area:
    alias: living_room
    sequence:
    - service: vacuum.send_command
      data:
        command: spot_area
        entity_id: vacuum.deebot
        params:
          area: 0
```

**Comment by 0endive** [comment]
> Looks like you have the script under the deebot domain and not script.
> 
> Your config should look like this
> 
> ```
> deebot:
>   username: username
>   password: password
>   country: XX
>   continent: XX
>   supported_features:
>       - start
>       - pause
>       - stop
>       - return_home
>       - fan_speed
>       - battery
>       - status
>       - send_command
>       - locate
>       - clean_spot
>       - turn_on
>       - turn_off
> script:     
>   vacuum_script_clean_area:
>     alias: living_room
>     sequence:
>     - service: vacuum.send_command
>       data:
>         command: spot_area
>         entity_id: vacuum.deebot
>         params:
>           area: 0
> ```

Thank you very much, it wasn’t clear in the instruction to add the code under script. 

I am able to add living_room script and can see it as entity however when I click, it is doing auto clean as opposed to select area. 

Also, How can I add multiple areas and/or map locations. Please let me know.

Thanks.

**Comment by Swanky-Bubbles** [comment]
Ooops, missed that part, make sure your area number is in quotes

```
script:     
  vacuum_script_clean_area:
    alias: living_room
    sequence:
    - service: vacuum.send_command
      data:
        command: spot_area
        entity_id: vacuum.deebot
        params:
          area: "0"
```

if you want multiple areas at once just separate by comma 

```
script:     
  vacuum_script_clean_area_0_1:
    alias: area_0_1
    sequence:
    - service: vacuum.send_command
      data:
        command: spot_area
        entity_id: vacuum.deebot
        params:
          area: "0, 1"
```

**Comment by 0endive** [comment]
That worked like a charm, Thanks.

My question about adding multiple areas is about adding multiple alias, such as alias: living_room alias: dining_room. Using either areas or map coordinates.

Thanks

**Comment by Swanky-Bubbles** [comment]
Ah got it, you'd do that like this:

```
script:     
  vacuum_script_clean_living_room:
    alias: living_room
    sequence:
    - service: vacuum.send_command
      data:
        command: spot_area
        entity_id: vacuum.deebot
        params:
          area: "0"

  vacuum_script_clean_dining_room:
    alias: dining_room
    sequence:
    - service: vacuum.send_command
      data:
        command: spot_area
        entity_id: vacuum.deebot
        params:
          area: "1"
```
More reference on scripts here: https://www.home-assistant.io/docs/scripts/
